spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
  flyway:
    clean-disabled: true  # Disable clean in production for safety
    clean-on-validation-error: false  # Don't auto-clean in production
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: noreply@timeaway.com
  from-name: TimeAway

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION} # Must be set in production
app:
  jwt:
    refresh-token:
      expiration: ${JWT_REFRESH_EXPIRATION} # Must be set in production

logging:
  level:
    root: ERROR
    dev.elieweb.timeaway: INFO
    org.springframework: WARN
    org.hibernate: WARN
  file:
    name: /var/log/timeaway/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 