spring:
  application:
    name: timeaway
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  task:
    scheduling:
      pool:
        size: 5
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-version: 0
    clean-on-validation-error: true
    clean-disabled: false
  security:
    oauth2:
      client:
        registration:
          azure-ad:
            provider: azure-ad
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - offline_access
              - User.Read
              - User.ReadBasic.All
            client-name: Azure AD
            redirect-uri: ${AZURE_REDIRECT_URI:https://staging-api.timeaway.com/api/v1/auth/microsoft/callback}
            client-authentication-method: post
            authorization-grant-type: authorization_code
        provider:
          azure-ad:
            issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
            authorization-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/discovery/v2.0/keys
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: preferred_username
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# SendGrid Configuration
sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: staging-noreply@timeaway.com
  from-name: TimeAway Staging

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:3600000}

app:
  frontend:
    url: ${APP_FRONTEND_URL:https://staging.timeaway.com}
  api:
    url: ${APP_API_URL:https://staging-api.timeaway.com}
  jwt:
    refresh-token:
      expiration: ${JWT_REFRESH_EXPIRATION:86400000}
  file-storage:
    location: ${FILE_STORAGE_LOCATION:/app/uploads}
    max-file-size: 5MB
    allowed-content-types:
      - application/pdf
      - application/msword
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document
      - image/jpeg
      - image/png
  file-upload:
    max-file-size: 5242880  # 5MB in bytes
    allowed-content-types:
      - application/pdf
      - application/msword
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document
      - image/jpeg
      - image/png

azure:
  activedirectory:
    tenant-id: ${AZURE_TENANT_ID}
    active-directory-groups: ${AZURE_AD_GROUPS:}

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  packages-to-scan: dev.elieweb.timeaway

logging:
  level:
    dev.elieweb.timeaway: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.oauth2: DEBUG
    org.springframework.security.oauth2: TRACE

# MailJet Configuration
mailjet:
  api:
    key: ${MAILJET_API_KEY}
    secret: ${MAILJET_API_SECRET}
  sender:
    email: ${MAILJET_SENDER_EMAIL}
    name: TimeAway 