spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:staging-db}:${DB_PORT:5432}/${DB_NAME:timeaway_staging_db}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    clean-disabled: false
    clean-on-validation-error: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# SendGrid Configuration
sendgrid:
  from-email: staging-noreply@timeaway.com
  from-name: TimeAway Staging

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour default
app:
  jwt:
    refresh-token:
      expiration: ${JWT_REFRESH_EXPIRATION:86400000} # 24 hours default

logging:
  level:
    dev.elieweb.timeaway: DEBUG
    org.springframework: INFO
    org.hibernate: INFO 